examples/app.py

The data in partial_update_pet function is a dictionary type, can't get key and value one time.

Fix examples/app.py partial_update_pet bug

---

README.md
docs/comparison.md
mkdocs.yml

Thanks @sloria and @jab for the suggestion to add this chapter.

Add docs chapter "Comparison and Motivations"

---

CHANGES.md
apiflask/app.py
apiflask/settings.py
docs/configuration.md
docs/docs.md
tests/test_settings.py

Add configuration variable OPENAPI_VERSION

---

docs/acknowledgement.md
docs/alterinatives.md
docs/api-docs.md
docs/authors.md
docs/docs.md
docs/migrating.md
docs/swagger.md
docs/tools/index.md
docs/usage.md
mkdocs.yml

Add more documentation

---

CHANGES.md
README.md
apiflask/__init__.py
apiflask/decorators.py
apiflask/exceptions.py
docs/alterinatives.md
docs/migrating.md
docs/openapi.md
docs/response.md
docs/schema.md
docs/security.md
docs/usage.md
examples/app.py
tests/test_exceptions.py

Rename abort_json to abort

---

CHANGES.md
apiflask/app.py
setup.cfg
tests/test_decorator_auth_required.py

Support to use the auth_required decorator on app-wide before_request functions

---

CHANGES.md
apiflask/route.py
docs/migrating.md
docs/usage.md
tests/test_route.py

- Use original class name as the endpoint for MethodView classes
- Allow passing methods in route for MethodView class
Checklist:

Improve class-based views

---

apiflask/app.py
apiflask/fields.py
examples/README.md
examples/orm/app.py
examples/requirements.txt

This PR also ignores the UserWarning from Flask-Marshmallow.

Add ORM example with Flask-SQLAlchemy

---

.github/workflows/tests.yml
apiflask/app.py
apiflask/security.py
apiflask/types.py

And disable docs check temporarily.

Fix type hints for Flask 2.0

---

apiflask/__init__.py
apiflask/app.py
apiflask/blueprint.py
apiflask/decorators.py
apiflask/exceptions.py
apiflask/fields.py
apiflask/helpers.py
apiflask/openapi.py
apiflask/route.py
apiflask/schemas.py
apiflask/security.py
apiflask/settings.py
apiflask/types.py
apiflask/validators.py
setup.cfg

- Fix typing of Schema argument
- Enable more mypy checks
- import typing as t
- Export top-level name explicitly

Improve typing

---

CHANGES.md
apiflask/app.py
tests/test_async.py
tests/test_decorator_output.py

Add `ensure_sync` wapper in `dispatch_requeset`.
Checklist:

Fix async for Flask 2.0

---

.github/workflows/tests.yml
apiflask/app.py
tox.ini

Fix dispatch_request for Flask 1.1

---

CONTRIBUTING.md
docs/contributing.md
mkdocs.yml

[Documentation progress](https://github.com/greyli/apiflask/issues/35): 11/17.

Add contributing guide

---

.github/workflows/codeql-analysis.yml
src/apiflask/helpers.py

Update codeql-analysis branches to main.

Fix workflows branches

---

docs/openapi.md

Update supported OpenAPI schema object fields list

---

CHANGES.md
docs/comparison.md
docs/configuration.md
docs/openapi.md
src/apiflask/app.py
src/apiflask/settings.py
tests/test_openapi_paths.py
tests/test_settings_auto_behaviour.py
tests/test_settings_response_customization.py

Add new configs:
- AUTO_404_RESPONSE
- NOT_FOUND_DESCRIPTION
fixes #78
Checklist:

Support automatic 404 response

---

examples/README.md
examples/blueprint_tags/app.py
examples/openapi/app.py
examples/test_examples.py

Add OpenAPI and Blueprint Tags examples

---

docs/openapi.md

Add docs for app.spec attribute

---

CHANGES.md
README.md
docs/_templates/main.html
src/apiflask/__init__.py

This is the first stable version. From this version, all breaking changes will start with a deprecated warning. The project status warning is removed.

Release 0.8

---

CHANGES.md
docs/configuration.md
docs/schema.md
examples/README.md
examples/base_response/app.py
examples/test_examples.py
src/apiflask/app.py
src/apiflask/decorators.py
src/apiflask/openapi.py
src/apiflask/settings.py
src/apiflask/types.py
tests/test_base_response.py

Fixes #65
Also:
- Add config: BASE_RESPONSE_SCHEMA, BASE_RESPONSE_DATA_KEY
- Improve some types for schema, add OpenAPISchemaType
- Add example application
A minimal example:
```python
from apiflask import APIFlask, Schema, input, output, abort
from apiflask.fields import Integer, String, Field
from apiflask.validators import Length, OneOf
class BaseResponseSchema(Schema):
message = String()
status_code = Integer()
data = Field()  # the data key
app.config['BASE_RESPONSE_SCHEMA'] = BaseResponseSchema
app.config['BASE_RESPONSE_DATA_KEY '] = 'data'
pets = [
{'id': 0, 'name': 'Kitty', 'category': 'cat'},
{'id': 1, 'name': 'Coco', 'category': 'dog'},
{'id': 2, 'name': 'Flash', 'category': 'cat'}
]
class PetInSchema(Schema):
name = String(required=True, …
```

Support base response customization

---

docs/usage.md

Fix typo in docs/usage.md

---

src/apiflask/app.py

Checklist:
- [:heavy_check_mark:] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [:heavy_check_mark:] Add or update relevant docs, in the `docs` folder and in code docstring.
- [:heavy_multiplication_x:] Add an entry in `CHANGES.md` summarizing the change and linking to the issue and your username.
- [:heavy_multiplication_x:] Add `*Version changed*` or `*Version added*` note in any relevant docs and docstring.
- [:heavy_check_mark:] Run `pytest` and `tox`, no tests failed.

Remove indentation spaces from docstrings as reflected in APIFairy

---

CHANGES.md
docs/usage.md
examples/pagination/app.py
src/apiflask/app.py
src/apiflask/helpers.py
tests/schemas.py
tests/test_app.py
tests/test_decorator_output.py

Reuse headers from Werkzeug exceptions for JSON error response

---

.github/workflows/tests.yml
tox.ini

https://github.com/actions/setup-python/issues/244

Replace deprecated pypy3 with pypy-3.8

---

docs/usage.md

- fixes #<issue number>
Checklist:

missing a " ' "

---

src/apiflask/app.py
tests/test_decorator_auth_required.py
tests/test_settings_auto_behaviour.py

- Improve the security handling code
- Remove the app-level auth_required detection (meaningless and not documented).
- Add tests for automatic 401 response on blueprint-level auth_required.
Checklist:

Refactor and improve the security handling

---

CHANGES.md
src/apiflask/app.py
tests/test_route.py

Fix the bp detection for endpoints contain a dot

---

requirements/dev.txt
requirements/docs.txt
requirements/examples.txt
requirements/tests.in
requirements/tests.txt
requirements/typing.txt
src/apiflask/app.py
tests/test_app.py
tests/test_decorator_output.py

Also remove flake8 from test requirements

Update requirements and tests

---

docs/error-handling.md

Rework error handling docs

---

docs/api/fields.md
docs/api/validators.md
docs/docs.md
docs/request.md
docs/usage.md
mkdocs.yml

Add docs for request handling

---

docs/docs.md
docs/request.md
docs/response.md
docs/usage.md
mkdocs.yml
src/apiflask/fields.py
src/apiflask/helpers.py
src/apiflask/schemas.py

Add docs for response formatting

---

docs/docs.md
docs/schema.md
docs/usage.md
mkdocs.yml

Add docs for data schema

---

docs/authentication.md
docs/comparison.md
docs/docs.md
docs/request.md
docs/response.md
docs/schema.md
docs/security.md
docs/usage.md
mkdocs.yml

Add docs for authentication support

---

docs/schema.md

Fix typo in docs/schema.md
Checklist:

fix typo in docs/schema.md

---

docs/openapi.md

- fix typo in openapi.md
Checklist:

fix typo in openapi.md

---

examples/README.md
examples/auth/basic_auth/app.py
examples/auth/token_auth/app.py

Finish #262 basic auth
Checklist:

Example basic auth

---

src/apiflask/scaffold.py
tests/test_async.py

- fixes #288 
NOTE: Important to test this with flask >= 2.0
Checklist:

Ensure doc, auth_required, and input will run ensure_async

---

src/apiflask/openapi.py
tests/test_decorator_auth_required.py
tests/test_openapi_security.py

The scheme value should be in lowercase.

Fix OpenAPI security scheme value

---

CHANGES.md
docs/request.md
docs/usage.md
src/apiflask/scaffold.py

Add the missing path/view_args request location

---

CHANGES.md
docs/authentication.md
src/apiflask/app.py
tests/test_security.py

This makes it possible to use built-in auth function and external auth lib at the same time.
- fixes #293
Checklist:

Combine custom security schemes with existing values

---

docs/_templates/main.html
docs/docs.md

Add docs version select menu

---

docs/api/fields.md
docs/api/schemas.md
docs/api/security.md
docs/api/validators.md
docs/schema.md
examples/base_response/app.py

- Add external docs to API docs
- Make the base response example simpler
fixes #313

Update API docs and base response example

---

CHANGES.md
README.md
docs/comparison.md
docs/migrating.md
src/apiflask/app.py
src/apiflask/types.py
tests/test_app.py

Automatic serialize list return value to JSON

---

examples/auth/token_auth/app.py

token_auth examples程序字典中的``id``键少了引号，运行会报``TypeError: keys must be str, int, float, bool or None, not builtin_function_or_method``
Checklist:

Fix token_auth example application

---

src/apiflask/route.py
src/apiflask/scaffold.py

Use type(MethodView) instead of MethodViewType

---

src/apiflask/settings.py

- Use unpkg.com for Swagger UI
- Use cdn.redoc.ly for Redoc

Update the CDN server of Swagger UI and Redoc

---

mkdocs.yml

Add Persian Translation to the `mkdocs.yml` file by alphabetical order.

Add Persian Translation

---

CHANGES.md
requirements/dev.txt
requirements/docs.txt
requirements/examples.txt
requirements/tests.txt
requirements/typing.txt
src/apiflask/fields.py

Add Enum field from marshmallow 3.18

---

CHANGES.md
src/apiflask/app.py
src/apiflask/scaffold.py
tests/schemas.py
tests/test_decorator_input.py

Allow path parameters overriding

---

CHANGES.md
src/apiflask/app.py
tests/test_app.py

Support to use custom apispec plugins with `spec_plugins` param

---

docs/usage.md

Fix typos in docs/usage

---

CHANGES.md
src/apiflask/route.py
tests/test_route.py

explicitly check if view_func.view_class is MethodViewType in add_url_rule

---

CHANGES.md
README.md
docs/migrating.md
docs/usage.md
examples/cbv/app.py
setup.cfg
setup.py
src/apiflask/app.py
src/apiflask/route.py
src/apiflask/scaffold.py
src/apiflask/types.py
src/apiflask/views.py
tests/test_app.py
tests/test_blueprint.py
tests/test_decorator_auth_required.py
tests/test_decorator_doc.py
tests/test_decorator_input.py
tests/test_decorator_output.py
tests/test_route.py
tests/test_settings_auto_behaviour.py

- Create apiflask.views module
- Raise error if using MethodView from flask.views
- Refactor the code to collect spec from view classes
- Remove the Flask<2.2 restriction
fixes #341
Checklist:

Fix and enhance the class-based view support

---

CHANGES.md
src/apiflask/scaffold.py
tests/test_decorator_input.py

Remove the validation of input location

---

CHANGES.md
docs/configuration.md
src/apiflask/ui_templates.py

Make config items of Function type in SWAGGER_UI_CONFIG work

---

docs/configuration.md

Add docs for config SECURITY_SCHEMES

---

CHANGES.md

fixes #<issue number>
Checklist:

fix 'supprt' typo in CHANGES.md file

---

.github/workflows/tests.yml
CHANGES.md
README.md
setup.py
src/apiflask/app.py
src/apiflask/scaffold.py
src/apiflask/views.py
tests/test_async.py
tests/test_openapi_tags.py
tox.ini

Drop Flask 1.x support

---

docs/api-docs.md
docs/configuration.md
docs/migrating.md
docs/openapi.md
docs/usage.md
examples/openapi/app.py
tests/test_decorator_input.py

- Fix outdated import statements
- Remove highlight noises in the code snippets
- Add keyword argument names.

Remove unnecessary code snippet highlights

---

CHANGES.md
docs/usage.md
src/apiflask/app.py
src/apiflask/scaffold.py
tests/test_decorators.py
tests/test_openapi_basic.py
tests/test_openapi_blueprint.py
tests/test_settings_api_docs.py

Remove previously deprecated code

---

CHANGES.md
docs/schema.md
src/apiflask/fields.py
tests/test_fields.py

Add Config field

---

docs/openapi.md
docs/usage.md

docs: checking bit misspell

---

docs/request.md
examples/README.md
examples/file_upload/app.py

The keyword argument of `form_and_files` should be `form_and_files_data`.

Correct err in docs and add example application for file uploading

---

tests/test_openapi_tags.py

Fix Flask version warning

---

examples/dataclass/app.py

Proposing more example for dataclass use.

More examples of default values, description and example

---

CHANGES.md
docs/openapi.md
src/apiflask/app.py
src/apiflask/openapi.py
src/apiflask/scaffold.py
tests/test_base_response.py

- Update changelog for 2.1.0
- Re-organize spec response-related methods
Checklist:

Fix base response schema inconsistency issue

---

CHANGES.md
NOTICE
docs/request.md
docs/schema.md
examples/file_upload/app.py
src/apiflask/helpers.py
src/apiflask/validators.py
tests/test_helpers.py
tests/test_validators.py

Add file validators for File field

---

examples/base_response/app.py

Fix typo in base response example.

fix typo in base response example

---

docs/configuration.md

Add a note for `BASE_RESPONSE_DATA_KEY`.
fixes #574

docs(configuration.md): add a note for `BASE_RESPONSE_DATA_KEY`

---

pyproject.toml

Fix configuration errors in `pyproject.toml`.

fix `spec` command

---

CHANGES.md
docs/openapi.md
src/apiflask/app.py
src/apiflask/scaffold.py
tests/test_openapi_extensions.py

Support adding custom field to operation object (view function) #571

---

.github/workflows/tests.yml
pyproject.toml
tox.ini

Fix Codecov CI

---

CHANGES.md
examples/dataclass/app.py
examples/test_examples.py
tests/test_app.py
tests/test_async.py
tests/test_base_response.py
tests/test_blueprint.py
tests/test_decorator_auth_required.py
tests/test_decorator_doc.py
tests/test_decorator_input.py
tests/test_decorator_output.py
tests/test_openapi_basic.py
tests/test_openapi_extensions.py
tests/test_openapi_info.py
tests/test_openapi_paths.py
tests/test_openapi_security.py
tests/test_openapi_tags.py
tests/test_route.py
tests/test_schemas.py
tests/test_security.py
tests/test_settings_auto_behaviour.py
tests/test_settings_openapi_fields.py
tests/test_settings_response_customization.py

test(examples): fix sqlalchemy version usage warnings in tests

---

CHANGES.md
requirements/dev.txt
requirements/docs.txt
requirements/examples.txt
requirements/min-versions.txt
requirements/tests.txt
requirements/typing.txt
src/apiflask/app.py

* Update release note
* Update deps.

Release 2.2.0

---

src/apiflask/route.py
tests/test_route.py

fix(#618): `MethodView` with subclass

---

src/apiflask/scaffold.py

Add return type information from APIFlask route method helpers

---

docs/authors.md

🎉 Welcome @FarmerChillax to the team!

Add new maintainer @FarmerChillax
