- CHANGES.md
- apiflask/__init__.py
- apiflask/app.py
- apiflask/settings.py
- tests/test_app.py
- tests/test_settings.py
Add new configs:
- `JSON_SPEC_MIMETYPE`
- `YAML_SPEC_MIMETYPE`
Remove config:
-  `SPEC_FORMAT`
Use `flask.jsonify` to generate a response object for dict response to prevent multiple content-type headers.
ref: https://github.com/pallets/flask/issues/3628
> Support to customize spec MIME type

- apiflask/app.py
Default version of the api should be "0.1.0", not "1.0.0".
> Fix typos in APIFlask docstring

- CHANGES.md
- apiflask/app.py
- apiflask/decorators.py
- apiflask/settings.py
- examples/app.py
- tests/test_decorators.py
- tests/test_settings.py
- Fix the support to pass an empty dict as schema for 204 response.
- Do not add `content` into spec for 204 response.
- Fix type annotation for schema and auth object.
Fix #11
> Improve 204 response handling

- CHANGES.md
- apiflask/app.py
- apiflask/decorators.py
- tests/test_decorators.py
Add a new `examples` for `@input` and `@output` decorators to pass multiple example values for request/response body:
```py
pet_examples = {
'example foo': {
'summary': 'an example of foo',
'value': {'name': 'foo', 'id': 1}
},
'example bar': {
'summary': 'an example of bar',
'value': {'name': 'bar', 'id': 2}
},
}
@app.get('/pets/<int:pet_id>')
@output(PetOutSchema, examples=pet_examples)
def get_pet(pet_id):
if pet_id > len(pets) - 1:
abort_json(404)
return pets[pet_id]
```
Checklist:
> Support set multiple examples for request/response body

- CHANGES.md
- apiflask/app.py
- apiflask/decorators.py
- tests/test_decorators.py
Actually, without this PR, the `role` and `tag` argument can also handle list value. This change basically used to make the API more consistent since we have `example` and `examples`. 
Example usage for roles:
```py
@app.get('/baz')
@auth_required(auth, roles=['admin', 'moderator'])
def baz():
return auth.current_user
```
Example usage for tags:
```py
@app.get('/bar')
@doc(tags=['foo', 'bar'])
def bar():
pass
```
Checklist:
> Add auth_required(roles) and doc(tags) arguments for list value

- apiflask/app.py
- apiflask/route.py
- tests/test_app.py
Some extension will create the blueprint, APIFlask needs to skip them when generating the OpenAPI spec file.
Checklist:
> Skip raw blueprint from OpenAPI generating

- CHANGES.md
- apiflask/decorators.py
- docs/migrating.md
- tests/test_decorator_output.py
Allow returning a `Response` object in a view function decorated with `output`. In this case, APIFlask will do nothing but return it directly.
> Return Response object directly in output decorator

- CHANGES.md
- README.md
- apiflask/decorators.py
- tests/test_decorator_output.py
A fix for Flask 2.0's async support.
```py
@app.get('/')
async def say_hello():
await asyncio.sleep(1)
return {'message': 'Hello!'}
@app.get('/pets/<int:pet_id>')
@output(PetOutSchema)
async def get_pet(pet_id):
if pet_id > len(pets) - 1:
abort(404)
return pets[pet_id]
```
Checklist:
> Support using async views for Flask 2.0

- apiflask/__init__.py
- apiflask/app.py
- apiflask/decorators.py
- apiflask/exceptions.py
- apiflask/security.py
- tests/test_exceptions.py
Rename the following decorators from Marshmallow:
- pre_load -> before_load
- post_load -> after_load
- pre_dump -> before_dump
- post_dump -> after_dump
- validates -> validate
- validates_schema -> validate_schema
Not sure if it's a good idea, but this is definitely what I want to do. The four hooks are changed to match the naming style in Flask (i.e., `before_request`, `after_request`, etc.). The `validates` -> `validate` change meant to make the names more simple.
This change will introduce an API difference between APIFlask and Marshmallow, I will address these changes at the beginning of the schema docs (working in progress).
> Import and rename decorators from Marshmallow

- CHANGES.md
- apiflask/app.py
- apiflask/exceptions.py
- apiflask/helpers.py
- tests/test_helpers.py
Add a `default` parameter for `get_reason_phrase` helper, defaults to `Unknown`.
Checklist:
> Add default parameter for get_reason_phrase

- CHANGES.md
- apiflask/app.py
- tests/test_app.py
In Flask 2.0, the static route expects a keyword argument for filename/path.
- fixes #52
Checklist:
> Fix static request dispatch for Flask 2.0

- apiflask/app.py
- tests/test_app.py
Continues #53
Improve the if statement to except endpoint end with `static`.
Checklist:
> Improve static request dispatch

- CHANGES.md
- apiflask/app.py
- tests/test_async.py
Example:
```python
@app.error_processor
async def custom_error_processor(status_code, message, detail, headers):
return {'foo': 'test'}, status_code, headers
```
Also rewrite some docstring.
Checklist:
> Support using async error processor and spec processor

- CHANGES.md
- apiflask/app.py
- tests/test_openapi_tags.py
With this PR, the endpoints in the child blueprint will be tagged with the correct name:
Checklist:
> Fix auto-tag support for nesting blueprint

- CHANGES.md
- apiflask/app.py
- tests/test_openapi_blueprint.py
Example usage:
```py
app = APIFlask(__name__, openapi_blueprint_url_prefix='/api')
```
Then the spec and docs will be available at `/api/openapi.json`, `/api/docs`, etc.
Checklist:
> Support set the url prefix of the OpenAPI blueprint

- CHANGES.md
- apiflask/commands.py
- apiflask/settings.py
- docs/api/commands.md
- docs/configuration.md
- docs/openapi.md
- mkdocs.yml
- setup.py
- tests/conftest.py
- tests/test_commands.py
- tests/test_settings_openapi_fields.py
- tests/test_settings_openapi_spec.py
```
$ flask spec --help
Usage: flask spec [OPTIONS]
The command (`flask spec`) to output the OpenAPI spec to stdout or a file.
Execute `flask spec --help` to see the usage.
Options:
-f, --format [json|yaml|yml]  The format of the spec, defaults to
SPEC_FORMAT config.
-o, --output PATH             The file path to the spec file, defauts to
LOCAL_SPEC_PATH config.
-i, --indent INTEGER          The indent for JSON spec, defauts to
LOCAL_SPEC_JSON_INDENT config.
--help                        Show this message and exit.
```
- fixes #61
Checklist:
> Add `flask sepc` command to output the spec to stdout or file

- CHANGES.md
- apiflask/app.py
- apiflask/commands.py
- docs/configuration.md
- docs/openapi.md
- tests/test_openapi_blueprint.py
- tests/test_settings_openapi_spec.py
> Remove support for automatic spec format detection

- CHANGES.md
- apiflask/app.py
- apiflask/settings.py
- docs/configuration.md
- docs/openapi.md
- tests/test_commands.py
- tests/test_openapi_basic.py
- tests/test_settings_openapi_spec.py
Example usage:
```python
from pathlib import Path
app.config['SYNC_LOCAL_SPEC'] = True
app.config['LOCAL_SPEC_PATH'] = Path(app.root_path) / 'openapi.json'
```
- fixes #68 
Checklist:
> Support to sync the local OpenAPI spec

- CHANGES.md
- src/apiflask/__init__.py
These undocumented name changes happened in #43, discussed in #62.
This PR will revert the name changes on pre/post decorators. The changes on validates* decorators are kept for now (but may revert in the future when the related docs are published):
- validates -> validate
- validates_schema -> valdiate_schema
> Revert undocumented name changes on pre/post decorators

- CHANGES.md
- docs/openapi.md
- src/apiflask/app.py
- src/apiflask/decorators.py
- tests/test_decorator_doc.py
- tests/test_openapi_paths.py
With this PR, you can overwrite the response description with the `doc` decorator:
```
@app.get('/baz/<int:id>')  # this will automatically add a 404 response with default description ("Not found")
@doc(responses={404: 'Pet not found'})  # this will overwrite the default 404 response description
def baz():
pass
```
Checklist:
> Support overwriting response description with `doc` decorator

- CHANGES.md
- docs/configuration.md
- examples/openapi/app.py
- src/apiflask/app.py
- src/apiflask/settings.py
- tests/test_openapi_info.py
- tests/test_settings_auto_behaviour.py
- tests/test_settings_openapi_fields.py
- Add `INFO`.
- Rename the following configuration variables:
- `AUTO_PATH_SUMMARY` -> `AUTO_OPERATION_SUMMARY`
- `AUTO_PATH_DESCRIPTION` -> `AUTO_OPERATION_DESCRIPTION`
fixes #98, #99
Checklist:
> Improve configuration variables for OpenAPI fields

- CHANGES.md
- docs/schema.md
- src/apiflask/app.py
- tests/test_app.py
Example usage:
```python
from apiflask import APIFlask
def my_schema_name_resolver(schema):
name = schema.__class__.__name__
if name.endswith('Schema'):
name = name[:-6] or name
if schema.partial:
name += 'Partial'
return name
app.schema_name_resolver = my_schema_name_resolver
```
- fixes #105
Checklist:
> Support setting custom schema name resolver via the `APIFlask.schema_name_resolver` attribute

- CHANGES.md
- src/apiflask/app.py
- src/apiflask/exceptions.py
- src/apiflask/security.py
- src/apiflask/types.py
- tests/test_app.py
- tests/test_async.py
- tests/test_exceptions.py
- tests/test_openapi_basic.py
- tests/test_security.py
- Authentication error now calls app error processor function when `APIFlask(json_errors=True)`. The default HTTP reason phrase is used for auth errors.
- Always pass an `HTTPError` instance to error processors. When you set a custom error processor, now you need to accept an `HTTPError` instance as the argument. The `detail` and `headers` attribute of the instance will be empty dict if not set.
- Add an `error_processor` decorator for `HTTPTokenAuth` and `HTTPBasicAuth`, it can be used to register a custom error processor for auth errors.
- Move default error handlers into class.
fixes #107
Checklist:
> Pass an `HTTPError` instance to error processors and support registering auth error processor

- CHANGES.md
- docs/api-docs.md
- docs/configuration.md
- src/apiflask/settings.py
- src/apiflask/ui_templates.py
- tests/test_settings_api_docs.py
Example:
```python
app.config['REDOC_CONFIG'] = {'disableSearch': True, 'hideLoading': True}
```
Also change the way to initialize Redoc: `<redoc></redoc>` -> `<script>Redoc.init()</script>`.
- fixes #121
Checklist:
> Add `REDOC_CONFIG` to support config Redoc

- CHANGES.md
- docs/migrating.md
- docs/usage.md
- src/apiflask/route.py
- src/apiflask/types.py
- tests/test_route.py
This PR enables to register a view class (MethodView) with the `add_url_rule` method. APIFlask will record the OpenAPI spec info before calling the actual `add_url_rule` method.
- fixes #110
Checklist:
> Support using add_url_rule on view classes

- CHANGES.md
- docs/openapi.md
- examples/openapi/app.py
- src/apiflask/app.py
- src/apiflask/decorators.py
- src/apiflask/openapi.py
- tests/test_decorator_output.py
The `output` decorator now accepts a `links` argument for response links:
```py
@app.post('/pets')
@input(PetInSchema)
@output(
PetOutSchema,
201,
description='The pet you just created',
links={'getPetById': {
'operationId': 'getPet',
'parameters': {
'pet_id': '$response.body#/id'
}
}}
)
@doc(tag='Pet')
def create_pet(data):
...
```
- fixes #138
Checklist:
> Support setting OpenAPI response links via `@output(links=...)`

- CHANGES.md
- docs/error-handling.md
- src/apiflask/app.py
- src/apiflask/decorators.py
- src/apiflask/exceptions.py
- src/apiflask/security.py
- src/apiflask/types.py
- tests/test_app.py
- tests/test_exceptions.py
- tox.ini
Add custom error classes support for HTTPError, the `status_code` now is a keyword argument, defaults to 500.
- fixes #172
Checklist:
> Add custom error classes support for HTTPError

- docs/api/decorators.md
Since they have been moved to the APIFlask and APIBlueprint classes (their API docs will appear there).
This will also fix the mkdocstrings build issue ([TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'](https://app.netlify.com/sites/apiflask/deploys/621cd16584a28900076180e4)) coincidentally because the issue was caused by the typing of webargs...
> Remove the API page of decorators

- CHANGES.md
- docs/security.md
- mkdocs.yml
- src/apiflask/app.py
- src/apiflask/settings.py
- tests/test_decorator_doc.py
- tests/test_settings_openapi_fields.py
- Add config `SECURITY_SCHEMES` and `app.security_schemes` attribute.
- Add `security` parameter to `app.doc()`.
Example:
```python
app.security_schemes = {
'ApiKeyAuth': {
'type': 'apiKey',
'in': 'header',
'name': 'X-API-Key',
}
}
@app.post('/pets')
@app.input(PetInSchema)
@app.output(PetOutSchema, 201)
@app.doc(security='ApiKeyAuth')  # <--
def create_pet(data):
pet_id = len(pets)
data['id'] = pet_id
pets.append(data)
return pets[pet_id]
```
This makes it possible to use external auth libraries.
- fixes #186
Checklist:
> Support customizing operation security and security schemes

- CHANGES.md
- docs/openapi.md
- examples/openapi/app.py
- src/apiflask/scaffold.py
- tests/test_decorator_auth_required.py
- tests/test_decorator_doc.py
- tests/test_decorators.py
- tests/test_route.py
Use roles and tags instead:
```py
@app.get('/')
@app.auth_required(auth, roles=['admin'])
@app.doc(tags=['Foo'])
def hello():
return 'Hello'
```
- fixes #237
Checklist:
> Deprecate the role and tag parameters

- CHANGES.md
- src/apiflask/app.py
- src/apiflask/fields.py
- src/apiflask/scaffold.py
- tests/schemas.py
- tests/test_decorator_input.py
- tests/test_fields.py
File validators will be added later in a separate PR.
The OpenAPI validation failed due to https://github.com/p1c2u/openapi-spec-validator/issues/113.
- fixes #123
Checklist:
> Support parsing and generating OpenAPI spec for file uploads

- CHANGES.md
- src/apiflask/fields.py
- src/apiflask/scaffold.py
- tests/test_decorator_input.py
Expose webargs's `DelimitedList` and `DelimitedTuple` fields.
- fixes #254
Checklist:
> Support json_or_form location and webargs fields

- CHANGES.md
- src/apiflask/app.py
- tests/test_app.py
Even when json_error is set to False.
- fixes #171
Checklist:
> Always apply custom error processor to HTTP errors

- docs/error-handling.md
- docs/openapi.md
- docs/request.md
- docs/schema.md
- docs/usage.md
- fix typo in openapi.md
Checklist:
> Fix incorrect admonition types

- docs/error-handling.md
Instance of apiflask.HTTPBasicAuth should be "auth"
- fixes #<issue number>
Checklist:
> Fix typo in docs/request-handling

- CHANGES.md
- setup.cfg
- src/apiflask/commands.py
- Add an `apiflask` console script to prevent overwriting `flask`.
- Add a short help text for the `flask spec` command.
fixes #312
> Fix CLI entry point setup

- tests/test_async.py
Implemented  a fixture for the "skip async test" function since all test in that file will requires Flask > 2.0
suggested by [jonasps](https://github.com/jonasps) and [greyli](https://github.com/greyli) 
apiflask/tests/test_async.py
Before
```
def skip_flask1(app):
if not hasattr(app, 'ensure_sync'):
pytest.skip('This test requires Flask 2.0 or higher')
```
After
```
@pytest.fixture(autouse=True)
def skip_async_test(app):
if not hasattr(app, 'ensure_sync'):
pytest.skip('This test requires Flask 2.0 or higher')
```
To improve it
- fixes #318 
Checklist:
> Simplify the async-related tests

- .github/workflows/tests.yml
- src/apiflask/app.py
- tox.ini
- Test against Python 3.10, 3.11
- Follow Flask's CI setup
- Update setup-python to v4
- Add cache support for pip
- Ignore docs changes
fixes: #297
fixes: #298
fixes: #299
> Improve CI setup and test against Python 3.10/3.11

- CHANGES.md
- src/apiflask/ui_templates.py
- tests/test_settings_api_docs.py
So we don't need to handle the basePath value.
> Set default Elements router to hash

- src/apiflask/app.py
- tests/test_app.py
1. In flask2.2,  use `_request_ctx_stack` will cause a warning, and it will be removed in flask2.3
2. In flask2.2, some unit test will raise [AssertionError](https://github.com/pallets/flask/blob/main/src/flask/app.py#L720). I try to mofidy the route order to fix this
some other unittest of flask2.2 can't pass is caused by the [class-based views issue](https://github.com/apiflask/apiflask/issues/341).
Checklist:
> for compat with flask 2.2

- tests/test_base_response.py
I think this test can't from the client side's request, maybe we can directly call the view function
Checklist:
> fix test base_response data key

- setup.py
- src/apiflask/app.py
Flask changed the signature of the view function created by view classes in the 2.2 version (https://github.com/pallets/flask/pull/4624), which now only accepts keyword-only arguments.
Temp fix for #341.
> Pin Flask < 2.2 as a temp fix for CBV support

- README.md
- docs/migrating.md
- docs/usage.md
- examples/cbv/app.py
Using the `route` on view classes has a drawback that it can't accept user-defined arguments. Besides, there is a note in Flask class view docs indicating the route can't be used on the view class. It may confuse users.
The PR remove the use of `route` on view classes in docs and examples. This will be deprecated in 1.2, and removed in 2.0.
> Prefer to use `add_url_rule` for view classes in docs and examples

- netlify.toml
After changing the build image, the deployment will fail with `pip install .` (ModuleNotFound: flask-marshmallow). This is a temp fix for this issue, I install these packages before running the pip install command.
> Fix Netlify build command

- CHANGES.md
- src/apiflask/app.py
- src/apiflask/openapi.py
- tests/test_openapi_basic.py
- Fix the bypass for the Blueprint static endpoint
- Improve the bypass rule for static and OpenAPI endpoints
- Add bypass rule for Flask-DebugToolbar
fixes #344
fixes #369
Checklist:
> Improve endpoint bypassing for OpenAPI spec

- CHANGES.md
- README.md
- docs/schema.md
- src/apiflask/app.py
- src/apiflask/schemas.py
- tests/test_commands.py
When generating the spec file with the `flask spec` command, the output should be deterministic. This PR changes the default set class of `Schema` class to `OrderedSet`, so that the schema fields will be in order by default. 
P.S. There is already a PR in marshmallow for this (https://github.com/marshmallow-code/marshmallow/pull/1896). We can remove this change when that PR is merged.
- fixes #373
- fixes #385
Checklist:
> Set schema fields in order by default

- CHANGES.md
- docs/configuration.md
- docs/docs.md
- docs/tips.md
- mkdocs.yml
- src/apiflask/app.py
- src/apiflask/exceptions.py
- src/apiflask/scaffold.py
- src/apiflask/settings.py
- tests/test_openapi_basic.py
- tests/test_settings_auto_behaviour.py
- Set default `servers` field
- Add `AUTO_SERVERS` config
- Add `Tips` docs chapter
fixes #377
fixes #334
Checklist:
> Support generating a default `servers` field

- CHANGES.md
- src/apiflask/scaffold.py
- tests/test_decorator_output.py
Fix the not-iterable exception occurred when a `@app.output()` decorated view function directly return a custom class.
fixes #384
Checklist:
> Fix the not-iterable exception occurred when directly returning a custom class

- CHANGES.md
- src/apiflask/app.py
- tests/test_openapi_basic.py
Some Flask extensions use add_url_rule to create routes from methods.
Related PR:
- https://github.com/apiflask/apiflask/pull/375
- https://github.com/apiflask/apiflask/pull/347
fixes #406
Checklist:
> Bypass OpenAPI spec generation for view methods

- CHANGES.md
- docs/configuration.md
- docs/openapi.md
- src/apiflask/app.py
- src/apiflask/settings.py
- tests/test_openapi_basic.py
Add a `SPEC_PROCESSOR_PASS_OBJECT` to control the argument type of the spec processor. Example usage:
```python
from apiflask import APIFlask
app.config['SPEC_PROCESSOR_PASS_OBJECT'] = True
class FooSchema(Schema):
id = Integer()
@app.spec_processor
def update_spec(spec):
spec.title = 'Updated Title'
spec.components.schema('Foo', schema=FooSchema)  # add a schema manually
return spec
```
fixes #213
Checklist:
> Support passing APISpec object to spec processor

- CHANGES.md
- src/apiflask/openapi.py
- src/apiflask/security.py
- tests/test_openapi_security.py
- tests/test_settings_openapi_fields.py
Example usage:
```py
auth = HTTPTokenAuth(header="X-Example-Key", security_scheme_name="api_token")
```
Generated spec:
```json
"securitySchemes":{"api_token":{"in":"header","name":"X-Example-Key","type":"apiKey"}}
```
fixes #410
Checklist:
> Add `security_scheme_name` to customize OpenAPI security key

- CHANGES.md
- docs/openapi.md
- examples/basic/app.py
- src/apiflask/app.py
- src/apiflask/openapi.py
- src/apiflask/scaffold.py
- tests/test_decorator_output.py
Add a `content_type` parameter to the `output` decorator:
```py
@app.post('/image')
@app.output(ImageOutSchema, content_type='image/png')
def get_image():
pass
```
fixes #357
Checklist:
> Support customizing the media/content type of the response

- docs/openapi.md
This fixes a few typos I noticed while reading about ImageOutSchema in the OpenAPI docs.
> Fix typos in openapi.md

- CHANGES.md
- docs/openapi.md
- src/apiflask/openapi.py
- src/apiflask/schemas.py
- tests/test_schemas.py
Example:
```py
from apiflask.schemas import FileSchema
@app.get('/files/<filename>')
@app.output(FileSchema, content_type='image/png')
def get_file(filename):
return ...
```
fixes #447
Checklist:
> Add `FileSchema` for file response

- .github/workflows/tests.yml
- CHANGES.md
- README.md
- docs/usage.md
- examples/orm/app.py
- examples/pagination/app.py
- mkdocs.yml
- requirements/dev.txt
- requirements/docs.txt
- requirements/examples.txt
- requirements/tests.txt
- requirements/typing.txt
- setup.cfg
- setup.py
- src/apiflask/app.py
- tests/test_decorator_input.py
- tox.ini
- Drop Python 3.7 support.
- Update dependencies.
- Remove outdated docs and code.
- Update mkdocs config.
> Update dependencies and remove outdated code & docs

- CHANGES.md
- docs/openapi.md
- src/apiflask/app.py
- tests/schemas.py
- tests/test_decorator_doc.py
Enhance the `doc` decorator to support passing a complete response spec for the `responses` parameter. For example:
```py
@app.doc(responses={
404: {
'description': 'Custom error',
'content': {
'application/json': {
'schema': SomeErrorSchema
}
}
}
})
```
fixes #327
Checklist:
> Support complete custom response spec

- src/apiflask/app.py
- src/apiflask/scaffold.py
- src/apiflask/types.py
Update the typing and documentation on the `responses` parameter of the `doc` decorator to match the implementation changes introduced in version 2.0.0 via #458.
Fixes #466.
I'm not sure why mypy isn't complaining about the type mismatch, but I think the parameter typing merits expansion after the 2.0.0 changes. I reworded the documentation a bit but I'm open to feedback or adjustments on it.
Checklist:
> Update typing and documentation for `responses` parameter on `doc` decorator

- src/apiflask/fields.py
Fix a typo in `fields.py` where the doc should use `files_data` instead of `files`. This is the only typo of its kind. The rest of the documentation and example codes already use the correct form.
> Fix typo in fields doc: files -> files_data

- CHANGES.md
- docs/openapi.md
- src/apiflask/app.py
- tests/test_decorator_doc.py
This PR modifies the code that handles `@app.doc(responses=...)`. The proposed implementation deals with cases where
a `dict` is passed.
The previous behavior assumed the passed dict would be used as the OpenAPI definition of the view's responses. This proposed implementation instead merges the contents of the passed dict taking into account the `content` key of each
status code. This is done in order to preserve whatever information might have already been automatically generated in
previous steps, namely what had been added while processing `app.output()`.
This means that with the current PR, APIFlask would preserve a view's main response media type, while also allowing
the addition of other, secondary media types, thus addressing the contents of issue #494
fixes #494
Checklist:
- [] …
> Allow adding multiple media types for a response

- src/apiflask/openapi.py
Sorry! I missed an added parameter [`ma_plugin`](https://github.com/apiflask/apiflask/blob/870ee6b0f264687e7ef2946c7af8d5976ea8107b/src/apiflask/openapi.py#L173) in [`add_response()`](https://github.com/apiflask/apiflask/blob/870ee6b0f264687e7ef2946c7af8d5976ea8107b/src/apiflask/openapi.py#L163C5-L163C17).
> fix typo: missing parameter `ma_plugin`

- docs/usage.md
There is a slight difference between APIFlask and Flask-HTTPAuth which misled my friend(Not me really).
Access the current user object in Flask-HTTPAuth is with `auth.current_user()`. But `auth.current_user` in APIFlask(No brackets).
So I suggest adding a tip for it.
> docs(usage.md): add a tip

- src/apiflask/exceptions.py
`typing.NoReturn` can help the type checkers narrow down the types.
For example:
```python
def my_view():
user: User | None = token_auth.current_user
if user is None:
abort(401)
return {"username": user.name}   # no error
```
fixes #<issue number>
Checklist:
> fix: correct the return type of abort()

- README.md
- setup.py
- src/apiflask/schemas.py
As of marshmallow 3.20.0 (released 2023-07-20), OrderedSet is the default set_class.
> Remove override of set_class in Schema

- src/apiflask/helpers.py
- tests/test_helpers.py
The old `get_filestorage_size` get the size by `len(file.read())` which triggers a read operation and consumes additional memory.
Old version:
```python
def get_filestorage_size(file: FileStorage) -> int:
size = len(file.read())
file.stream.seek(0)
return size
```
The new `get_filestorage_size` get the size by `file.stream.getbuffer().nbytes` which returns the number of bytes of the data directly without any extra overhead.
New version:
```python
def get_filestorage_size(file: FileStorage) -> int:
size: int = file.stream.getbuffer().nbytes  # type: ignore
return size
```
> perf: optimize `get_filestorage_size`

- CHANGES.md
- docs/openapi.md
- src/apiflask/commands.py
- tests/test_commands.py
Added support for a `--quiet/-q` option to the `flask spec` command, so that output can be written to a file without also writing to stdout.
Fixes #548.
Checklist:
> Add support for a --quiet flag to the flask spec command

- docs/openapi.md
- examples/README.md
Updated the README.md in the /examples directory and the openapi.md in the /docs directory  correctly point to the OpenAPI example locations.
> doc: correct the OpenAPI example links in the documentation

- .pre-commit-config.yaml
- requirements/dev.txt
- requirements/docs.txt
- requirements/examples.txt
- requirements/min-versions.txt
- requirements/tests.txt
- requirements/typing.txt
- tests/test_fields.py
<del>**Pin flask-marshmallow==1.2.1** for two important bug fixes below:</del>
- [Fix File field when it receives an empty value](https://github.com/marshmallow-code/flask-marshmallow/pull/301)
- [Fix validate.FileSize to handle SpooledTemporaryFile](https://github.com/marshmallow-code/flask-marshmallow/pull/300)
<del>**Pin flask==2.2.0 and werkzeug==2.2.0** because [flask-marshmallow updated min version of flask](https://github.com/marshmallow-code/flask-marshmallow/pull/289).</del>
<del>**Pin Flask-HTTPAuth==4.4.0** because [`safe_str_cmp` is deprecated and has been removed in `Werkzeug 2.1`](https://github.com/miguelgrinberg/Flask-HTTPAuth/pull/126).</del>
**Update flake8 hook to 7.0.0** to be [compatible with `python3.12`](https://github.com/PyCQA/flake8/issues/1701).
Add a test for …
> Update dependencies and add tests for empty file field

- .github/workflows/release.yml
Use GitHub Actions to automatically release the package to PyPI.
> Publish automatically using GitHub Actions

- CHANGES.md
- src/apiflask/app.py
- src/apiflask/blueprint.py
- src/apiflask/exceptions.py
- src/apiflask/helpers.py
- src/apiflask/openapi.py
- src/apiflask/route.py
- src/apiflask/scaffold.py
- src/apiflask/schemas.py
- src/apiflask/security.py
- src/apiflask/settings.py
- src/apiflask/types.py
Add `from __future__ import annotations` to every file that may be annotated. Replace the vast majority of old `Union`, `Optional`, and types with their modern equivalent syntax.
Checklist:
> Use postponed evaluation of annotations

- docs/docs.md
This PR addresses a 404 error when clicking the `Migrating from flask` option in the [documentation index](https://apiflask.com/docs/) page. Here's a screenshot:
I also made a separate entry for migrating from FlaskRESTPlus/RestX. I didn't create an open issue for this as the change is very simple.
Checklist:
> docs: Fix broken doc link regarding flask migrations

- README.md
- Fixes the broken link to migrations on the README
Checklist:
> fix broken migrations link

- .github/workflows/tests.yml
- CHANGES.md
- docs/request.md
- src/apiflask/app.py
- src/apiflask/scaffold.py
- tests/test_decorator_input.py
The `json_or_form` location will generate the following spec:
```yaml
requestBody:
content:
application/json:
schema:
type: object
properties:
...
application/x-www-form-urlencoded:
schema:
type: object
properties:
...
```
fixes #600
Checklist:
> Fix OpenAPI spec for multiple content types (json_for_form)

- CHANGES.md
- src/apiflask/scaffold.py
- tests/test_decorator_input.py
Modifies the behavior of specifying `validation=False` on the `@input` decorator to include input schema documentation in the generated API spec, while still skipping validation on the request input.
Fixes #626.
Checklist:
> Include input documentation in API spec when skipping validation

- CHANGES.md
- src/apiflask/scaffold.py
- tests/test_decorator_input.py
Modified the `@input` data loading logic for the `validation=False` case by replacing the hand-rolled data loading implementation with an implementation from elements within the `webargs` library. Also fixed an undocumented issue where the `arg_name` parameter was not properly handled when input validation is skipped.
Fixes #629.
Checklist:
> Modify input validation skip to use webargs implementation

- CHANGES.md
- src/apiflask/app.py
- tests/test_openapi_headers.py
Modified the response headers generation to omit the `in` and `name` fields from being included in the generated specification, per OAS 3.0.0+.
Fixes #631.
Checklist:
> Modify response headers to be compliant with OAS 3.0.0+

- CHANGES.md
- src/apiflask/app.py
- tests/test_openapi_blueprint.py
Add parameter 'docs_oauth2_redirect_path_external' to support absolute redirect url.
Fixes #602.
Checklist:
> Add parameter 'docs_oauth2_redirect_path_external' to support absolute redirect url.

- CHANGES.md
- docs/usage.md
The documentation mentions `@app.route` but the example mistakenly uses `@app.post`.
> Fix app.route example in usage documentation page

- CHANGES.md
- docs/configuration.md
- examples/openapi/static_docs/index.html
- src/apiflask/settings.py
UNPKG has not been actively maintained and ~~has been down since `Mar 15, 2025`~~ was down from Mar 15, 2025, 2:00 AM and down for 18 hours (https://github.com/unpkg/unpkg/issues/412). Migrating to jsDelivr means a more stable and reliant service.
The PR replaces UNPKG in the redoc default settings w/ jsDelivr. The docs has also been updated correspondingly.
Checklist:
> Replace UNPKG w/ jsDelivr

- .github/workflows/tests.yml
- tests/test_decorator_doc.py
- tests/test_decorator_input.py
- tests/test_decorator_output.py
With the Python version 3.8 all unit test works fine, but up Python 3.9 there is an extra 'additionalProperties': False within the rv.json['components']['schemas']['MyName'] and rv.json['components']['schemas']['CustomHTTPError'], so I use the if sys.version_info >= (3, 9) to assert with additionalProperties and else to assert w/o additionalProperties, which this will eliminate the inconsisten behavior between different Python Version
fixes #<issue number>
Checklist:
- [ X ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ X ] Add or update relevant docs, in the `docs` folder and in code docstring.
- [ X ] Run `pytest` and `tox`, no tests failed.
> Tom Yang codekitchen Sprint7 task1
